// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Platform.DBAccess;

#nullable disable

namespace Platform.DBAccess.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Platform.DataEntities.AirRankingEntity", b =>
                {
                    b.Property<int>("RankingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("FinishedValue")
                        .HasColumnType("REAL");

                    b.Property<double>("PlanValue")
                        .HasColumnType("REAL");

                    b.Property<string>("WorkshopName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RankingId");

                    b.ToTable("AirRankings");
                });

            modelBuilder.Entity("Platform.DataEntities.ComponentEntity", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("ComponentId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("Platform.DataEntities.DeviceAlarmEntity", b =>
                {
                    b.Property<string>("AlarmNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlarmContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlarmValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SolveTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VarName")
                        .HasColumnType("TEXT");

                    b.Property<string>("VarNum")
                        .HasColumnType("TEXT");

                    b.HasKey("AlarmNum");

                    b.ToTable("DeviceAlarms");
                });

            modelBuilder.Entity("Platform.DataEntities.DeviceEntity", b =>
                {
                    b.Property<string>("DeviceNum")
                        .HasColumnType("TEXT");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FlowDirection")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<int>("Rotate")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<double>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("DeviceNum");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Platform.DataEntities.DevicePropEntity", b =>
                {
                    b.Property<int>("DevicePropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DevicePropId");

                    b.ToTable("DeviceProps");
                });

            modelBuilder.Entity("Platform.DataEntities.DeviceVarEntity", b =>
                {
                    b.Property<string>("VarNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Modulus")
                        .HasColumnType("REAL");

                    b.Property<double>("Offset")
                        .HasColumnType("REAL");

                    b.Property<string>("VarAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VarName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VarType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VarNum");

                    b.ToTable("DeviceVars");
                });

            modelBuilder.Entity("Platform.DataEntities.DeviceWarningEntity", b =>
                {
                    b.Property<int>("WarningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WarningId");

                    b.ToTable("DeviceWarnings");
                });

            modelBuilder.Entity("Platform.DataEntities.ManualControlEntity", b =>
                {
                    b.Property<int>("ControlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ControlId");

                    b.ToTable("ManualControls");
                });

            modelBuilder.Entity("Platform.DataEntities.MonitorRecordEntity", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlarmNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RecordValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("VarName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VarNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecordId");

                    b.ToTable("MonitorRecords");
                });

            modelBuilder.Entity("Platform.DataEntities.MonitorSettingEntity", b =>
                {
                    b.Property<int>("SettingNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VarNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SettingNum");

                    b.ToTable("MonitorSettings");
                });

            modelBuilder.Entity("Platform.DataEntities.PropEntity", b =>
                {
                    b.Property<int>("PropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PropType")
                        .HasColumnType("INTEGER");

                    b.HasKey("PropId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Platform.DataEntities.SevenAirEntity", b =>
                {
                    b.Property<int>("AirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Air")
                        .HasColumnType("TEXT");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AirId");

                    b.ToTable("SevenAirs");
                });

            modelBuilder.Entity("Platform.DataEntities.SevenLeakEntity", b =>
                {
                    b.Property<int>("LeakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Leak")
                        .HasColumnType("TEXT");

                    b.HasKey("LeakId");

                    b.ToTable("SevenLeaks");
                });

            modelBuilder.Entity("Platform.DataEntities.SevenPowerEntity", b =>
                {
                    b.Property<int>("PowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Power")
                        .HasColumnType("TEXT");

                    b.HasKey("PowerId");

                    b.ToTable("SevenPowers");
                });

            modelBuilder.Entity("Platform.DataEntities.SysUserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("SysUsers");
                });

            modelBuilder.Entity("Platform.DataEntities.TrendAxisEntity", b =>
                {
                    b.Property<string>("AxisNum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShowSeperator")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShowTitle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelFormater")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Maximum")
                        .HasColumnType("REAL");

                    b.Property<double>("Minimum")
                        .HasColumnType("REAL");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrendNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AxisNum");

                    b.ToTable("TrendAxises");
                });

            modelBuilder.Entity("Platform.DataEntities.TrendEntity", b =>
                {
                    b.Property<string>("TrendNum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShowLegend")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrendName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TrendNum");

                    b.ToTable("Trends");
                });

            modelBuilder.Entity("Platform.DataEntities.TrendSectionEntity", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AxisNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("SectionId");

                    b.ToTable("TrendSections");
                });

            modelBuilder.Entity("Platform.DataEntities.TrendSeriesEntity", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ANum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrendNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VarNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SeriesId");

                    b.ToTable("TrendSerieses");
                });

            modelBuilder.Entity("Platform.DataEntities.VarAlarmConfEntity", b =>
                {
                    b.Property<string>("ConfNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlarmContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompareValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VarNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ConfNum");

                    b.ToTable("VarAlarmConfs");
                });
#pragma warning restore 612, 618
        }
    }
}
