<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
    <PackageReference Include="NModbus4" Version="2.1.0" />
    <PackageReference Include="System.IO.Ports" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Platform.DataEntities\Platform.DataEntities.csproj" />
  </ItemGroup>

</Project>
